# Generated by Django 2.1 on 2018-08-22 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid projectId', regex='^[a-zA-Z0-9]+$')], verbose_name='Project ID')),
                ('projectName', models.CharField(max_length=100)),
                ('jobs', models.TextField()),
            ],
        ),
    ]
