# Generated by Django 2.1 on 2018-08-22 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iNum',
            field=models.CharField(default=2, max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 7', regex='^I[0-9]{7}$')], verbose_name='I Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=32425, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(default=1423),
            preserve_default=False,
        ),
    ]
