# Generated by Django 2.1 on 2018-08-22 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180822_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='iNum',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 7', regex='^I[0-9]{6}$')], verbose_name='I Number'),
        ),
    ]
