# Generated by Django 2.1 on 2018-08-26 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180822_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iNum', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Incorrect I-Number', regex='^I[0-9]{6}$')], verbose_name='I Number')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='iNum',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Incorrect I-Number', regex='^I[0-9]{6}$')], verbose_name='I Number'),
        ),
    ]
