# Generated by Django 2.1 on 2018-08-27 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180826_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activation',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='iNum',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='skills',
        ),
        migrations.AddField(
            model_name='activation',
            name='code',
            field=models.CharField(default='invalid', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
