# Generated by Django 2.1 on 2018-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20180827_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='bookedTill',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='currentProject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='no designation', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(default='L1', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='interests',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='isManagement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='isStaffed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='skillSets',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tier',
            field=models.CharField(default='T1', max_length=2),
        ),
    ]
