# Generated by Django 2.1 on 2018-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20180901_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bookedTill',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='currentProject',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(default='None', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='interests',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skillSets',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tier',
            field=models.CharField(default='None', max_length=2),
        ),
    ]
